// This file will be auto-generated by Supabase CLI
// Run: pnpm supabase gen types typescript --project-id <project-id> > lib/types/database.ts
// For now, we define manual types that match our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          favicon_url: string | null
          primary_color: string
          secondary_color: string
          accent_color: string
          custom_domain: string | null
          custom_domain_verified: boolean
          portal_domain: string | null
          portal_domain_verified: boolean
          portal_branding: Json
          timezone: string
          currency: string
          date_format: string
          subscription_tier: string
          subscription_status: string
          stripe_customer_id: string | null
          trial_ends_at: string | null
          max_users: number
          max_storage_gb: number
          feature_flags: Json
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          name: string
          slug: string
          // Optional fields (have DB defaults)
          id?: string
          primary_color?: string
          secondary_color?: string
          accent_color?: string
          custom_domain_verified?: boolean
          portal_domain_verified?: boolean
          portal_branding?: Json
          timezone?: string
          currency?: string
          date_format?: string
          subscription_tier?: string
          subscription_status?: string
          max_users?: number
          max_storage_gb?: number
          feature_flags?: Json
          settings?: Json
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          logo_url?: string | null
          favicon_url?: string | null
          custom_domain?: string | null
          portal_domain?: string | null
          stripe_customer_id?: string | null
          trial_ends_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>
      Relationships: []
      }
      users: {
        Row: {
          id: string
          tenant_id: string
          auth_user_id: string | null
          email: string
          first_name: string | null
          last_name: string | null
          phone: string | null
          avatar_url: string | null
          role_id: string | null
          is_active: boolean
          notification_prefs: Json
          device_tokens: Json
          calendar_provider: string | null
          calendar_sync_enabled: boolean
          last_login_at: string | null
          settings: Json
          practice_filter_preference: string
          created_at: string
          updated_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          email: string
          // Optional fields (have DB defaults)
          id?: string
          is_active?: boolean
          notification_prefs?: Json
          device_tokens?: Json
          calendar_sync_enabled?: boolean
          settings?: Json
          practice_filter_preference?: string
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          auth_user_id?: string | null
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          avatar_url?: string | null
          role_id?: string | null
          calendar_provider?: string | null
          last_login_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      Relationships: []
      }
      roles: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          permissions: Json
          is_system: boolean
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          name: string
          // Optional fields (have DB defaults)
          id?: string
          permissions?: Json
          is_system?: boolean
          created_at?: string
          // Optional nullable fields
          description?: string | null
        }
        Update: Partial<Database['public']['Tables']['roles']['Insert']>
      Relationships: []
      }
      contacts: {
        Row: {
          id: string
          tenant_id: string
          contact_type: string
          first_name: string | null
          last_name: string | null
          middle_name: string | null
          preferred_name: string | null
          date_of_birth: string | null
          organization_name: string | null
          organization_id: string | null
          job_title: string | null
          email_primary: string | null
          email_secondary: string | null
          phone_primary: string | null
          phone_secondary: string | null
          phone_type_primary: string
          phone_type_secondary: string | null
          website: string | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          province_state: string | null
          postal_code: string | null
          country: string
          source: string | null
          source_detail: string | null
          referred_by: string | null
          engagement_score: number
          last_contacted_at: string | null
          last_interaction_type: string | null
          interaction_count: number
          email_opt_in: boolean
          sms_opt_in: boolean
          opt_in_date: string | null
          opt_in_source: string | null
          has_portal_access: boolean
          portal_user_id: string | null
          portal_last_login: string | null
          custom_fields: Json
          notes: string | null
          is_active: boolean
          is_archived: boolean
          created_by: string | null
          created_at: string
          updated_at: string
          immigration_data: Json
          email_notifications_enabled: boolean
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          // Optional fields (have DB defaults)
          id?: string
          contact_type?: string
          phone_type_primary?: string
          country?: string
          engagement_score?: number
          interaction_count?: number
          email_opt_in?: boolean
          sms_opt_in?: boolean
          has_portal_access?: boolean
          email_notifications_enabled?: boolean
          custom_fields?: Json
          is_active?: boolean
          is_archived?: boolean
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          first_name?: string | null
          last_name?: string | null
          middle_name?: string | null
          preferred_name?: string | null
          date_of_birth?: string | null
          organization_name?: string | null
          organization_id?: string | null
          job_title?: string | null
          email_primary?: string | null
          email_secondary?: string | null
          phone_primary?: string | null
          phone_secondary?: string | null
          phone_type_secondary?: string | null
          website?: string | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          province_state?: string | null
          postal_code?: string | null
          source?: string | null
          source_detail?: string | null
          referred_by?: string | null
          last_contacted_at?: string | null
          last_interaction_type?: string | null
          opt_in_date?: string | null
          opt_in_source?: string | null
          portal_user_id?: string | null
          portal_last_login?: string | null
          notes?: string | null
          created_by?: string | null
          immigration_data?: Json
        }
        Update: Partial<Database['public']['Tables']['contacts']['Insert']>
      Relationships: []
      }
      pipelines: {
        Row: {
          id: string
          tenant_id: string
          name: string
          pipeline_type: string
          practice_area: string | null
          is_default: boolean
          is_active: boolean
          on_enter_automation_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          name: string
          // Optional fields (have DB defaults)
          id?: string
          pipeline_type?: string
          is_default?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          practice_area?: string | null
          on_enter_automation_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['pipelines']['Insert']>
      Relationships: []
      }
      pipeline_stages: {
        Row: {
          id: string
          tenant_id: string
          pipeline_id: string
          name: string
          sort_order: number
          color: string
          description: string | null
          is_win_stage: boolean
          is_lost_stage: boolean
          win_probability: number
          on_enter_automation_id: string | null
          rotting_days: number | null
          card_display_fields: Json
          required_fields: Json
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          pipeline_id: string
          name: string
          // Optional fields (have DB defaults)
          id?: string
          sort_order?: number
          color?: string
          is_win_stage?: boolean
          is_lost_stage?: boolean
          win_probability?: number
          card_display_fields?: Json
          required_fields?: Json
          created_at?: string
          // Optional nullable fields
          description?: string | null
          on_enter_automation_id?: string | null
          rotting_days?: number | null
        }
        Update: Partial<Database['public']['Tables']['pipeline_stages']['Insert']>
      Relationships: []
      }
      practice_areas: {
        Row: {
          id: string
          tenant_id: string
          name: string
          color: string
          default_pipeline_id: string | null
          default_folder_structure: Json
          default_task_template_id: string | null
          is_active: boolean
          is_enabled: boolean
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          name: string
          // Optional fields (have DB defaults)
          id?: string
          color?: string
          default_folder_structure?: Json
          is_active?: boolean
          is_enabled?: boolean
          created_at?: string
          // Optional nullable fields
          default_pipeline_id?: string | null
          default_task_template_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['practice_areas']['Insert']>
      Relationships: []
      }
      matters: {
        Row: {
          id: string
          tenant_id: string
          matter_number: string | null
          title: string
          description: string | null
          practice_area_id: string | null
          matter_type: string | null
          pipeline_id: string | null
          stage_id: string | null
          stage_entered_at: string
          responsible_lawyer_id: string | null
          originating_lawyer_id: string | null
          team_member_ids: string[]
          date_opened: string
          date_closed: string | null
          statute_of_limitations: string | null
          next_deadline: string | null
          billing_type: string
          estimated_value: number | null
          weighted_value: number | null
          total_billed: number
          total_paid: number
          trust_balance: number
          hourly_rate: number | null
          status: string
          priority: string
          custom_fields: Json
          visibility: string
          created_by: string | null
          created_at: string
          updated_at: string
          case_type_id: string | null
          matter_type_id: string | null
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          title: string
          // Optional fields (have DB defaults)
          id?: string
          stage_entered_at?: string
          team_member_ids?: string[]
          date_opened?: string
          billing_type?: string
          total_billed?: number
          total_paid?: number
          trust_balance?: number
          status?: string
          priority?: string
          custom_fields?: Json
          visibility?: string
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          matter_number?: string | null
          description?: string | null
          practice_area_id?: string | null
          matter_type?: string | null
          matter_type_id?: string | null
          pipeline_id?: string | null
          stage_id?: string | null
          responsible_lawyer_id?: string | null
          originating_lawyer_id?: string | null
          date_closed?: string | null
          statute_of_limitations?: string | null
          next_deadline?: string | null
          estimated_value?: number | null
          weighted_value?: number | null
          hourly_rate?: number | null
          created_by?: string | null
          case_type_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['matters']['Insert']>
      Relationships: []
      }
      matter_contacts: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          contact_id: string
          role: string
          is_primary: boolean
          notes: string | null
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          matter_id: string
          contact_id: string
          // Optional fields (have DB defaults)
          id?: string
          role?: string
          is_primary?: boolean
          created_at?: string
          // Optional nullable fields
          notes?: string | null
        }
        Update: Partial<Database['public']['Tables']['matter_contacts']['Insert']>
      Relationships: []
      }
      tasks: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string | null
          contact_id: string | null
          title: string
          description: string | null
          assigned_to: string | null
          assigned_by: string | null
          due_date: string | null
          due_time: string | null
          start_date: string | null
          priority: string
          estimated_minutes: number | null
          status: string
          completed_at: string | null
          completed_by: string | null
          parent_task_id: string | null
          follow_up_days: number | null
          depends_on_task_id: string | null
          blocks_task_id: string | null
          is_recurring: boolean
          recurrence_rule: Json | null
          created_via: string
          automation_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
          notes: string | null
          timeline_end: string | null
          custom_checkbox: boolean
          is_deleted: boolean
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          title: string
          // Optional fields (have DB defaults)
          id?: string
          priority?: string
          status?: string
          is_recurring?: boolean
          created_via?: string
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          matter_id?: string | null
          contact_id?: string | null
          description?: string | null
          assigned_to?: string | null
          assigned_by?: string | null
          due_date?: string | null
          due_time?: string | null
          start_date?: string | null
          estimated_minutes?: number | null
          completed_at?: string | null
          completed_by?: string | null
          parent_task_id?: string | null
          follow_up_days?: number | null
          depends_on_task_id?: string | null
          blocks_task_id?: string | null
          recurrence_rule?: Json | null
          automation_id?: string | null
          created_by?: string | null
          notes?: string | null
          timeline_end?: string | null
          custom_checkbox?: boolean
          is_deleted?: boolean
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['tasks']['Insert']>
      Relationships: []
      }
      leads: {
        Row: {
          id: string
          tenant_id: string
          contact_id: string
          pipeline_id: string
          stage_id: string
          stage_entered_at: string
          source: string | null
          source_detail: string | null
          source_campaign: string | null
          utm_source: string | null
          utm_medium: string | null
          utm_campaign: string | null
          practice_area_id: string | null
          estimated_value: number | null
          weighted_value: number | null
          assigned_to: string | null
          engagement_score: number
          temperature: string
          status: string
          converted_matter_id: string | null
          converted_at: string | null
          lost_reason: string | null
          lost_detail: string | null
          next_follow_up: string | null
          follow_up_count: number
          notes: string | null
          custom_fields: Json
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          contact_id: string
          pipeline_id: string
          stage_id: string
          // Optional fields (have DB defaults)
          id?: string
          stage_entered_at?: string
          engagement_score?: number
          temperature?: string
          status?: string
          follow_up_count?: number
          custom_fields?: Json
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          source?: string | null
          source_detail?: string | null
          source_campaign?: string | null
          utm_source?: string | null
          utm_medium?: string | null
          utm_campaign?: string | null
          practice_area_id?: string | null
          estimated_value?: number | null
          weighted_value?: number | null
          assigned_to?: string | null
          converted_matter_id?: string | null
          converted_at?: string | null
          lost_reason?: string | null
          lost_detail?: string | null
          next_follow_up?: string | null
          notes?: string | null
          created_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['leads']['Insert']>
      Relationships: []
      }
      activities: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string | null
          contact_id: string | null
          activity_type: string
          title: string
          description: string | null
          entity_type: string | null
          entity_id: string | null
          user_id: string | null
          engagement_points: number
          metadata: Json
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          activity_type: string
          title: string
          // Optional fields (have DB defaults)
          id?: string
          engagement_points?: number
          metadata?: Json
          created_at?: string
          // Optional nullable fields
          matter_id?: string | null
          contact_id?: string | null
          description?: string | null
          entity_type?: string | null
          entity_id?: string | null
          user_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['activities']['Insert']>
      Relationships: []
      }
      tags: {
        Row: {
          id: string
          tenant_id: string
          name: string
          color: string
          entity_type: string | null
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          name: string
          // Optional fields (have DB defaults)
          id?: string
          color?: string
          created_at?: string
          // Optional nullable fields
          entity_type?: string | null
        }
        Update: Partial<Database['public']['Tables']['tags']['Insert']>
      Relationships: []
      }
      entity_tags: {
        Row: {
          id: string
          tenant_id: string
          tag_id: string
          entity_type: string
          entity_id: string
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          tag_id: string
          entity_type: string
          entity_id: string
          // Optional fields (have DB defaults)
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['entity_tags']['Insert']>
      Relationships: []
      }
      custom_field_definitions: {
        Row: {
          id: string
          tenant_id: string
          entity_type: string
          field_key: string
          field_label: string
          field_type: string
          options: Json | null
          is_required: boolean
          default_value: string | null
          sort_order: number
          practice_area_id: string | null
          show_on_card: boolean
          show_in_table: boolean
          is_active: boolean
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          entity_type: string
          field_key: string
          field_label: string
          field_type: string
          // Optional fields (have DB defaults)
          id?: string
          is_required?: boolean
          sort_order?: number
          show_on_card?: boolean
          show_in_table?: boolean
          is_active?: boolean
          created_at?: string
          // Optional nullable fields
          options?: Json | null
          default_value?: string | null
          practice_area_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['custom_field_definitions']['Insert']>
      Relationships: []
      }
      contact_relationships: {
        Row: {
          id: string
          tenant_id: string
          contact_id_a: string
          contact_id_b: string
          relationship_type: string
          reverse_type: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          contact_id_a: string
          contact_id_b: string
          relationship_type: string
          // Optional fields (have DB defaults)
          id?: string
          created_at?: string
          // Optional nullable fields
          reverse_type?: string | null
          notes?: string | null
        }
        Update: Partial<Database['public']['Tables']['contact_relationships']['Insert']>
      Relationships: []
      }
      notifications: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          title: string
          message: string | null
          notification_type: string | null
          entity_type: string | null
          entity_id: string | null
          channels: string[]
          is_read: boolean
          read_at: string | null
          is_pushed: boolean
          pushed_at: string | null
          priority: string
          created_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          user_id: string
          title: string
          // Optional fields (have DB defaults)
          id?: string
          channels?: string[]
          is_read?: boolean
          is_pushed?: boolean
          priority?: string
          created_at?: string
          // Optional nullable fields
          message?: string | null
          notification_type?: string | null
          entity_type?: string | null
          entity_id?: string | null
          read_at?: string | null
          pushed_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      Relationships: []
      }
      saved_views: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          name: string
          entity_type: string
          filters: Json
          sort_by: Json
          columns: Json
          view_type: string
          group_by: string | null
          is_default: boolean
          is_shared: boolean
          icon: string | null
          color: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          // Required fields (NOT NULL, no DB default)
          tenant_id: string
          name: string
          entity_type: string
          // Optional fields (have DB defaults)
          id?: string
          filters?: Json
          sort_by?: Json
          columns?: Json
          view_type?: string
          is_default?: boolean
          is_shared?: boolean
          created_at?: string
          updated_at?: string
          // Optional nullable fields
          user_id?: string | null
          group_by?: string | null
          icon?: string | null
          color?: string | null
        }
        Update: Partial<Database['public']['Tables']['saved_views']['Insert']>
      Relationships: []
      }
      documents: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string | null
          contact_id: string | null
          lead_id: string | null
          uploaded_by: string | null
          file_name: string
          file_type: string | null
          file_size: number | null
          storage_path: string
          description: string | null
          category: string
          tags: string[]
          is_archived: boolean
          created_at: string
          updated_at: string
          task_id: string | null
        }
        Insert: {
          tenant_id: string
          file_name: string
          storage_path: string
          id?: string
          category?: string
          tags?: string[]
          is_archived?: boolean
          created_at?: string
          updated_at?: string
          matter_id?: string | null
          contact_id?: string | null
          lead_id?: string | null
          task_id?: string | null
          uploaded_by?: string | null
          file_type?: string | null
          file_size?: number | null
          description?: string | null
        }
        Update: Partial<Database['public']['Tables']['documents']['Insert']>
      Relationships: []
      }
      notes: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string | null
          contact_id: string | null
          lead_id: string | null
          user_id: string | null
          content: string
          note_type: string
          is_pinned: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          content: string
          id?: string
          note_type?: string
          is_pinned?: boolean
          created_at?: string
          updated_at?: string
          matter_id?: string | null
          contact_id?: string | null
          lead_id?: string | null
          user_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['notes']['Insert']>
      Relationships: []
      }
      audit_logs: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          entity_type: string
          entity_id: string
          action: string
          changes: Json
          metadata: Json
          created_at: string
        }
        Insert: {
          tenant_id: string
          entity_type: string
          entity_id: string
          action: string
          id?: string
          changes?: Json
          metadata?: Json
          created_at?: string
          user_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          tenant_id: string
          stripe_subscription_id: string | null
          stripe_customer_id: string | null
          plan_tier: string
          status: string
          billing_interval: string
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          cancelled_at: string | null
          trial_ends_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          id?: string
          plan_tier?: string
          status?: string
          billing_interval?: string
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancelled_at?: string | null
          trial_ends_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['subscriptions']['Insert']>
      Relationships: []
      }
      billing_invoices: {
        Row: {
          id: string
          tenant_id: string
          stripe_invoice_id: string | null
          amount: number
          currency: string
          status: string
          invoice_url: string | null
          invoice_pdf: string | null
          period_start: string | null
          period_end: string | null
          created_at: string
        }
        Insert: {
          tenant_id: string
          id?: string
          amount?: number
          currency?: string
          status?: string
          created_at?: string
          stripe_invoice_id?: string | null
          invoice_url?: string | null
          invoice_pdf?: string | null
          period_start?: string | null
          period_end?: string | null
        }
        Update: Partial<Database['public']['Tables']['billing_invoices']['Insert']>
      Relationships: []
      }
      plan_features: {
        Row: {
          id: string
          plan_tier: string
          feature_key: string
          enabled: boolean
          limit_value: number | null
        }
        Insert: {
          plan_tier: string
          feature_key: string
          id?: string
          enabled?: boolean
          limit_value?: number | null
        }
        Update: Partial<Database['public']['Tables']['plan_features']['Insert']>
      Relationships: []
      }
      booking_pages: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          slug: string
          title: string
          description: string | null
          duration_minutes: number
          buffer_minutes: number
          working_hours: {
            start: string
            end: string
            days: number[]
          }
          timezone: string
          max_days_ahead: number
          min_notice_hours: number
          questions: Array<{
            id: string
            label: string
            type: 'text' | 'textarea' | 'select'
            required: boolean
            options?: string[]
          }>
          pipeline_id: string | null
          stage_id: string | null
          practice_area_id: string | null
          status: string
          is_active: boolean
          theme_color: string | null
          confirmation_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id: string
          slug: string
          title: string
          description?: string | null
          duration_minutes?: number
          buffer_minutes?: number
          working_hours?: unknown
          timezone?: string
          max_days_ahead?: number
          min_notice_hours?: number
          questions?: unknown
          pipeline_id?: string | null
          stage_id?: string | null
          practice_area_id?: string | null
          status?: string
          is_active?: boolean
          theme_color?: string | null
          confirmation_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['booking_pages']['Insert']>
        Relationships: []
      }
      booking_page_overrides: {
        Row: {
          id: string
          tenant_id: string
          booking_page_id: string
          override_date: string
          is_available: boolean
          start_time: string | null
          end_time: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          booking_page_id: string
          override_date: string
          is_available?: boolean
          start_time?: string | null
          end_time?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['booking_page_overrides']['Insert']>
        Relationships: []
      }
      appointments: {
        Row: {
          id: string
          tenant_id: string
          booking_page_id: string
          user_id: string
          contact_id: string | null
          lead_id: string | null
          appointment_date: string
          start_time: string
          end_time: string
          duration_minutes: number
          guest_name: string
          guest_email: string
          guest_phone: string | null
          guest_notes: string | null
          answers: Record<string, unknown>
          status: string
          cancellation_reason: string | null
          cancelled_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          booking_page_id: string
          user_id: string
          contact_id?: string | null
          lead_id?: string | null
          appointment_date: string
          start_time: string
          end_time: string
          duration_minutes: number
          guest_name: string
          guest_email: string
          guest_phone?: string | null
          guest_notes?: string | null
          answers?: unknown
          status?: string
          cancellation_reason?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['appointments']['Insert']>
        Relationships: []
      }
      time_entries: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          user_id: string
          entry_date: string
          duration_minutes: number
          hourly_rate: number | null
          description: string
          is_billable: boolean
          is_billed: boolean
          invoice_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          user_id: string
          description: string
          duration_minutes: number
          id?: string
          entry_date?: string
          hourly_rate?: number | null
          is_billable?: boolean
          is_billed?: boolean
          invoice_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['time_entries']['Insert']>
        Relationships: []
      }
      invoices: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          invoice_number: string
          contact_id: string | null
          issue_date: string
          due_date: string
          subtotal: number
          tax_amount: number
          total_amount: number
          amount_paid: number
          status: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          invoice_number: string
          due_date: string
          id?: string
          contact_id?: string | null
          issue_date?: string
          subtotal?: number
          tax_amount?: number
          total_amount?: number
          amount_paid?: number
          status?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['invoices']['Insert']>
        Relationships: []
      }
      invoice_line_items: {
        Row: {
          id: string
          tenant_id: string
          invoice_id: string
          description: string
          quantity: number
          unit_price: number
          amount: number
          time_entry_id: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          tenant_id: string
          invoice_id: string
          description: string
          id?: string
          quantity?: number
          unit_price?: number
          amount?: number
          time_entry_id?: string | null
          sort_order?: number
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['invoice_line_items']['Insert']>
        Relationships: []
      }
      payments: {
        Row: {
          id: string
          tenant_id: string
          invoice_id: string
          amount: number
          payment_date: string
          payment_method: string
          reference: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          tenant_id: string
          invoice_id: string
          amount: number
          id?: string
          payment_date?: string
          payment_method?: string
          reference?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['payments']['Insert']>
        Relationships: []
      }
      task_assignees: {
        Row: {
          id: string
          tenant_id: string
          task_id: string
          user_id: string
          role: string
          assigned_at: string
          assigned_by: string | null
        }
        Insert: {
          tenant_id: string
          task_id: string
          user_id: string
          id?: string
          role?: string
          assigned_at?: string
          assigned_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['task_assignees']['Insert']>
      Relationships: []
      }
      task_templates: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          practice_area_id: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          name: string
          id?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
          description?: string | null
          practice_area_id?: string | null
          created_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['task_templates']['Insert']>
      Relationships: []
      }
      task_template_items: {
        Row: {
          id: string
          tenant_id: string
          template_id: string
          title: string
          description: string | null
          priority: string
          due_days_offset: number | null
          sort_order: number
          assigned_role: string | null
          created_at: string
        }
        Insert: {
          tenant_id: string
          template_id: string
          title: string
          id?: string
          priority?: string
          sort_order?: number
          created_at?: string
          description?: string | null
          due_days_offset?: number | null
          assigned_role?: string | null
        }
        Update: Partial<Database['public']['Tables']['task_template_items']['Insert']>
      Relationships: []
      }
      // ================================================================
      // Immigration Practice Operating System Tables
      // ================================================================
      immigration_case_types: {
        Row: {
          id: string
          tenant_id: string
          name: string
          slug: string
          description: string | null
          is_active: boolean
          sort_order: number
          default_billing_type: string
          default_estimated_value: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          name: string
          slug: string
          id?: string
          is_active?: boolean
          sort_order?: number
          default_billing_type?: string
          created_at?: string
          updated_at?: string
          description?: string | null
          default_estimated_value?: number | null
        }
        Update: Partial<Database['public']['Tables']['immigration_case_types']['Insert']>
        Relationships: []
      }
      case_stage_definitions: {
        Row: {
          id: string
          tenant_id: string
          case_type_id: string
          name: string
          slug: string
          description: string | null
          sort_order: number
          color: string
          is_terminal: boolean
          requires_checklist_complete: boolean
          auto_tasks: Json
          created_at: string
        }
        Insert: {
          tenant_id: string
          case_type_id: string
          name: string
          slug: string
          id?: string
          sort_order?: number
          color?: string
          is_terminal?: boolean
          requires_checklist_complete?: boolean
          auto_tasks?: Json
          created_at?: string
          description?: string | null
        }
        Update: Partial<Database['public']['Tables']['case_stage_definitions']['Insert']>
        Relationships: []
      }
      checklist_templates: {
        Row: {
          id: string
          tenant_id: string
          case_type_id: string
          document_name: string
          description: string | null
          is_required: boolean
          sort_order: number
          category: string
          created_at: string
        }
        Insert: {
          tenant_id: string
          case_type_id: string
          document_name: string
          id?: string
          is_required?: boolean
          sort_order?: number
          category?: string
          created_at?: string
          description?: string | null
        }
        Update: Partial<Database['public']['Tables']['checklist_templates']['Insert']>
        Relationships: []
      }
      matter_immigration: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          case_type_id: string | null
          current_stage_id: string | null
          stage_entered_at: string
          stage_history: Json
          country_of_citizenship: string | null
          country_of_residence: string | null
          date_of_birth: string | null
          passport_number: string | null
          passport_expiry: string | null
          current_visa_status: string | null
          current_visa_expiry: string | null
          uci_number: string | null
          application_number: string | null
          date_filed: string | null
          date_biometrics: string | null
          date_medical: string | null
          date_interview: string | null
          date_decision: string | null
          date_landing: string | null
          prior_refusals: boolean
          prior_refusal_details: string | null
          has_criminal_record: boolean
          criminal_record_details: string | null
          has_medical_issues: boolean
          medical_issue_details: string | null
          language_test_type: string | null
          language_test_scores: Json | null
          education_credential: string | null
          eca_status: string | null
          crs_score: number | null
          work_experience_years: number | null
          canadian_work_experience_years: number | null
          spouse_included: boolean
          dependents_count: number
          employer_name: string | null
          lmia_number: string | null
          job_offer_noc: string | null
          provincial_nominee_program: string | null
          retainer_signed: boolean
          retainer_signed_at: string | null
          retainer_amount: number | null
          government_fees: number | null
          internal_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          id?: string
          stage_entered_at?: string
          stage_history?: Json
          prior_refusals?: boolean
          has_criminal_record?: boolean
          has_medical_issues?: boolean
          spouse_included?: boolean
          dependents_count?: number
          retainer_signed?: boolean
          created_at?: string
          updated_at?: string
          case_type_id?: string | null
          current_stage_id?: string | null
          country_of_citizenship?: string | null
          country_of_residence?: string | null
          date_of_birth?: string | null
          passport_number?: string | null
          passport_expiry?: string | null
          current_visa_status?: string | null
          current_visa_expiry?: string | null
          uci_number?: string | null
          application_number?: string | null
          date_filed?: string | null
          date_biometrics?: string | null
          date_medical?: string | null
          date_interview?: string | null
          date_decision?: string | null
          date_landing?: string | null
          prior_refusal_details?: string | null
          criminal_record_details?: string | null
          medical_issue_details?: string | null
          language_test_type?: string | null
          language_test_scores?: Json | null
          education_credential?: string | null
          eca_status?: string | null
          crs_score?: number | null
          work_experience_years?: number | null
          canadian_work_experience_years?: number | null
          employer_name?: string | null
          lmia_number?: string | null
          job_offer_noc?: string | null
          provincial_nominee_program?: string | null
          retainer_signed_at?: string | null
          retainer_amount?: number | null
          government_fees?: number | null
          internal_notes?: string | null
        }
        Update: Partial<Database['public']['Tables']['matter_immigration']['Insert']>
        Relationships: []
      }
      matter_checklist_items: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          checklist_template_id: string | null
          document_name: string
          description: string | null
          category: string
          is_required: boolean
          status: string
          document_id: string | null
          requested_at: string | null
          received_at: string | null
          approved_at: string | null
          approved_by: string | null
          notes: string | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          document_name: string
          id?: string
          category?: string
          is_required?: boolean
          status?: string
          sort_order?: number
          created_at?: string
          updated_at?: string
          checklist_template_id?: string | null
          description?: string | null
          document_id?: string | null
          requested_at?: string | null
          received_at?: string | null
          approved_at?: string | null
          approved_by?: string | null
          notes?: string | null
        }
        Update: Partial<Database['public']['Tables']['matter_checklist_items']['Insert']>
        Relationships: []
      }
      matter_deadlines: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          deadline_type: string
          deadline_type_id: string | null
          title: string
          description: string | null
          due_date: string
          status: string
          priority: string
          completed_at: string | null
          completed_by: string | null
          auto_generated: boolean
          source_field: string | null
          reminder_days: number[]
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          deadline_type: string
          title: string
          due_date: string
          id?: string
          deadline_type_id?: string | null
          status?: string
          priority?: string
          auto_generated?: boolean
          reminder_days?: number[]
          created_at?: string
          updated_at?: string
          description?: string | null
          completed_at?: string | null
          completed_by?: string | null
          source_field?: string | null
        }
        Update: Partial<Database['public']['Tables']['matter_deadlines']['Insert']>
        Relationships: []
      }
      automation_rules: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          is_active: boolean
          case_type_id: string | null
          matter_type_id: string | null
          trigger_type: string
          trigger_config: Json
          action_type: string
          action_config: Json
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          name: string
          trigger_type: string
          action_type: string
          id?: string
          is_active?: boolean
          trigger_config?: Json
          action_config?: Json
          sort_order?: number
          created_at?: string
          updated_at?: string
          description?: string | null
          case_type_id?: string | null
          matter_type_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['automation_rules']['Insert']>
        Relationships: []
      }
      // ── Phase 1: NorvaOS Multi-Practice ──────────────────────────────
      matter_types: {
        Row: {
          id: string
          tenant_id: string
          practice_area_id: string
          name: string
          description: string | null
          color: string
          icon: string | null
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          practice_area_id: string
          name: string
          id?: string
          description?: string | null
          color?: string
          icon?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_types']['Insert']>
        Relationships: []
      }
      matter_stage_pipelines: {
        Row: {
          id: string
          tenant_id: string
          matter_type_id: string
          name: string
          description: string | null
          is_default: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_type_id: string
          name: string
          id?: string
          description?: string | null
          is_default?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_stage_pipelines']['Insert']>
        Relationships: []
      }
      matter_stages: {
        Row: {
          id: string
          tenant_id: string
          pipeline_id: string
          name: string
          description: string | null
          color: string
          sort_order: number
          is_terminal: boolean
          auto_close_matter: boolean
          sla_days: number | null
          gating_rules: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          pipeline_id: string
          name: string
          id?: string
          description?: string | null
          color?: string
          sort_order?: number
          is_terminal?: boolean
          auto_close_matter?: boolean
          sla_days?: number | null
          gating_rules?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_stages']['Insert']>
        Relationships: []
      }
      deadline_types: {
        Row: {
          id: string
          tenant_id: string
          practice_area_id: string | null
          matter_type_id: string | null
          name: string
          description: string | null
          color: string
          default_days_offset: number | null
          is_hard: boolean
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          name: string
          id?: string
          practice_area_id?: string | null
          matter_type_id?: string | null
          description?: string | null
          color?: string
          default_days_offset?: number | null
          is_hard?: boolean
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['deadline_types']['Insert']>
        Relationships: []
      }
      matter_type_schema: {
        Row: {
          id: string
          tenant_id: string
          matter_type_id: string
          schema_version: number
          json_schema: Json
          ui_schema: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_type_id: string
          json_schema: Json
          id?: string
          schema_version?: number
          ui_schema?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_type_schema']['Insert']>
        Relationships: []
      }
      matter_custom_data: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          matter_type_id: string
          schema_version: number
          data: Json
          is_valid: boolean | null
          validation_errors: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          matter_type_id: string
          id?: string
          schema_version?: number
          data?: Json
          is_valid?: boolean | null
          validation_errors?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_custom_data']['Insert']>
        Relationships: []
      }
      workflow_templates: {
        Row: {
          id: string
          tenant_id: string
          matter_type_id: string
          name: string
          description: string | null
          stage_pipeline_id: string | null
          task_template_id: string | null
          checklist_template_id: string | null
          trigger_stage_id: string | null
          is_default: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_type_id: string
          name: string
          id?: string
          description?: string | null
          stage_pipeline_id?: string | null
          task_template_id?: string | null
          checklist_template_id?: string | null
          trigger_stage_id?: string | null
          is_default?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['workflow_templates']['Insert']>
        Relationships: []
      }
      matter_stage_state: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          pipeline_id: string
          current_stage_id: string
          entered_at: string
          previous_stage_id: string | null
          stage_history: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          pipeline_id: string
          current_stage_id: string
          id?: string
          entered_at?: string
          previous_stage_id?: string | null
          stage_history?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['matter_stage_state']['Insert']>
        Relationships: []
      }
      // ── Intake Forms ───────────────────────────────────────────
      intake_forms: {
        Row: {
          id: string
          tenant_id: string
          name: string
          slug: string
          description: string | null
          fields: Json
          settings: Json
          practice_area_id: string | null
          pipeline_id: string | null
          stage_id: string | null
          status: string
          is_active: boolean
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          name: string
          slug: string
          created_by: string
          id?: string
          description?: string | null
          fields?: Json
          settings?: Json
          practice_area_id?: string | null
          pipeline_id?: string | null
          stage_id?: string | null
          status?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['intake_forms']['Insert']>
        Relationships: []
      }
      intake_submissions: {
        Row: {
          id: string
          tenant_id: string
          form_id: string
          data: Json
          contact_id: string | null
          lead_id: string | null
          source_ip: string | null
          user_agent: string | null
          utm_source: string | null
          utm_medium: string | null
          utm_campaign: string | null
          status: string
          processed_at: string | null
          created_at: string
        }
        Insert: {
          tenant_id: string
          form_id: string
          id?: string
          data?: Json
          contact_id?: string | null
          lead_id?: string | null
          source_ip?: string | null
          user_agent?: string | null
          utm_source?: string | null
          utm_medium?: string | null
          utm_campaign?: string | null
          status?: string
          processed_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['intake_submissions']['Insert']>
        Relationships: []
      }
      automation_execution_log: {
        Row: {
          id: string
          tenant_id: string
          automation_rule_id: string
          matter_id: string
          trigger_event: string
          trigger_context: Json
          actions_executed: Json
          executed_at: string
          executed_by: string | null
        }
        Insert: {
          tenant_id: string
          automation_rule_id: string
          matter_id: string
          trigger_event: string
          id?: string
          trigger_context?: Json
          actions_executed?: Json
          executed_at?: string
          executed_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['automation_execution_log']['Insert']>
        Relationships: []
      }
      portal_links: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          contact_id: string | null
          token: string
          expires_at: string
          is_active: boolean
          created_by: string | null
          last_accessed_at: string | null
          access_count: number
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          token: string
          expires_at: string
          id?: string
          contact_id?: string | null
          is_active?: boolean
          created_by?: string | null
          last_accessed_at?: string | null
          access_count?: number
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['portal_links']['Insert']>
        Relationships: []
      }
      client_notifications: {
        Row: {
          id: string
          tenant_id: string
          matter_id: string
          contact_id: string
          notification_type: string
          subject: string
          body_html: string | null
          body_text: string | null
          channel: string
          status: string
          recipient_email: string | null
          resend_message_id: string | null
          error_message: string | null
          metadata: Json
          sent_at: string | null
          delivered_at: string | null
          opened_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          matter_id: string
          contact_id: string
          subject: string
          id?: string
          notification_type?: string
          body_html?: string | null
          body_text?: string | null
          channel?: string
          status?: string
          recipient_email?: string | null
          resend_message_id?: string | null
          error_message?: string | null
          metadata?: Json
          sent_at?: string | null
          delivered_at?: string | null
          opened_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['client_notifications']['Insert']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_current_tenant_id: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}
