/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * Directive 033: Sovereign Brand Injection  -  withSovereignHeader() PDF Wrapper
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Global header/footer renderer for all NorvaOS PDF documents.
 * Applies the firm's branding (logo, colours, letterhead layout, legal disclaimer)
 * to any PDF document. If no branding is configured, falls back to the
 * "Norva Default Prestige" placeholder so documents never look broken.
 *
 * Three layout presets:
 *   - classic:  Logo top-left, firm name right, address below
 *   - modern:   Logo centred above firm name, address centred below
 *   - minimal:  No logo, firm name only (text-based letterhead)
 *
 * Usage:
 *   const headerY = await drawSovereignHeader(pm, page, branding, fonts)
 *   // headerY = y-position after header  -  start document content here
 *
 *   drawSovereignFooter(page, branding, fonts)
 *   // Draws footer with legal disclaimer + "Generated by NorvaOS"
 */

import { PDFDocument, PDFPage, PDFFont, PDFImage, rgb } from 'pdf-lib'

// ── Types ────────────────────────────────────────────────────────────────────

export type LetterheadLayout = 'classic' | 'modern' | 'minimal'

export interface SovereignBranding {
  firmName: string
  firmAddress?: string | null

  // Logo  -  provide either logoBytes (for server-side) or logoUrl
  logoBytes?: Uint8Array | null
  logoMimeType?: 'image/png' | 'image/jpeg' | 'image/svg+xml' | null

  // Signature  -  transparent PNG bytes for auto-signing
  signatureBytes?: Uint8Array | null

  // Layout & colours
  letterheadLayout: LetterheadLayout
  primaryColor?: string | null   // Hex, e.g. '#1a3b65'
  secondaryColor?: string | null
  accentColor?: string | null

  // Footer
  legalDisclaimer?: string | null

  // Contact info (optional, for header)
  phone?: string | null
  fax?: string | null
  website?: string | null
}

// ── Constants ────────────────────────────────────────────────────────────────

const PAGE_WIDTH = 595
const PAGE_HEIGHT = 842
const MARGIN_LEFT = 50
const MARGIN_RIGHT = 50
const MARGIN_TOP = 50
const MARGIN_BOTTOM = 60
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT

const FONT_TITLE = 18
const FONT_BODY = 9
const FONT_SMALL = 7.5
const LINE_HEIGHT = 14

// Default Norva prestige colours
const NORVA_PRIMARY = rgb(0.15, 0.35, 0.65)
const NORVA_MID = rgb(0.45, 0.45, 0.45)
const NORVA_LIGHT = rgb(0.7, 0.7, 0.7)
const NORVA_ACCENT_LINE = rgb(0.2, 0.55, 0.35) // Emerald accent

// ── Hex to RGB helper ────────────────────────────────────────────────────────

function hexToRgb(hex: string): ReturnType<typeof rgb> {
  const cleaned = hex.replace('#', '')
  const r = parseInt(cleaned.substring(0, 2), 16) / 255
  const g = parseInt(cleaned.substring(2, 4), 16) / 255
  const b = parseInt(cleaned.substring(4, 6), 16) / 255
  return rgb(r, g, b)
}

function getPrimaryColor(branding: SovereignBranding): ReturnType<typeof rgb> {
  if (branding.primaryColor) {
    try { return hexToRgb(branding.primaryColor) } catch { /* fallback */ }
  }
  return NORVA_PRIMARY
}

// ── Logo Embedding ───────────────────────────────────────────────────────────

async function embedLogo(
  doc: PDFDocument,
  branding: SovereignBranding,
): Promise<PDFImage | null> {
  if (!branding.logoBytes || branding.logoBytes.length === 0) return null

  try {
    if (branding.logoMimeType === 'image/jpeg') {
      return await doc.embedJpg(branding.logoBytes)
    }
    // Default to PNG (SVG should be rasterised before passing in)
    return await doc.embedPng(branding.logoBytes)
  } catch (err) {
    console.warn('[sovereign-header] Failed to embed logo:', err)
    return null
  }
}

async function embedSignature(
  doc: PDFDocument,
  branding: SovereignBranding,
): Promise<PDFImage | null> {
  if (!branding.signatureBytes || branding.signatureBytes.length === 0) return null

  try {
    return await doc.embedPng(branding.signatureBytes)
  } catch (err) {
    console.warn('[sovereign-header] Failed to embed signature:', err)
    return null
  }
}

// ── Layout: Classic ──────────────────────────────────────────────────────────

function drawClassicHeader(
  page: PDFPage,
  branding: SovereignBranding,
  fonts: { regular: PDFFont; bold: PDFFont },
  logo: PDFImage | null,
): number {
  const primary = getPrimaryColor(branding)
  let y = PAGE_HEIGHT - MARGIN_TOP

  // Logo on the left (max 120w × 50h)
  if (logo) {
    const dims = logo.scaleToFit(120, 50)
    page.drawImage(logo, {
      x: MARGIN_LEFT,
      y: y - dims.height,
      width: dims.width,
      height: dims.height,
    })

    // Firm name to the right of logo
    const textX = MARGIN_LEFT + dims.width + 12
    page.drawText(branding.firmName, {
      x: textX,
      y: y - 14,
      size: FONT_TITLE,
      font: fonts.bold,
      color: primary,
    })

    // Contact info below firm name (if available)
    let infoY = y - 30
    if (branding.phone) {
      page.drawText(branding.phone, {
        x: textX, y: infoY, size: FONT_SMALL, font: fonts.regular, color: NORVA_MID,
      })
      infoY -= LINE_HEIGHT
    }
    if (branding.website) {
      page.drawText(branding.website, {
        x: textX, y: infoY, size: FONT_SMALL, font: fonts.regular, color: NORVA_MID,
      })
    }

    y -= Math.max(dims.height, 50) + 8
  } else {
    // No logo  -  firm name large, left-aligned
    page.drawText(branding.firmName, {
      x: MARGIN_LEFT,
      y,
      size: FONT_TITLE,
      font: fonts.bold,
      color: primary,
    })
    y -= 22
  }

  // Address lines
  if (branding.firmAddress) {
    const lines = branding.firmAddress.split('\n')
    for (const line of lines) {
      page.drawText(line, {
        x: MARGIN_LEFT, y, size: FONT_BODY, font: fonts.regular, color: NORVA_MID,
      })
      y -= LINE_HEIGHT
    }
  }

  // Emerald accent line
  y -= 6
  page.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 1.5,
    color: NORVA_ACCENT_LINE,
  })
  y -= 4

  // Thin grey separator
  page.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 0.5,
    color: NORVA_LIGHT,
  })
  y -= 16

  return y
}

// ── Layout: Modern ───────────────────────────────────────────────────────────

function drawModernHeader(
  page: PDFPage,
  branding: SovereignBranding,
  fonts: { regular: PDFFont; bold: PDFFont },
  logo: PDFImage | null,
): number {
  const primary = getPrimaryColor(branding)
  let y = PAGE_HEIGHT - MARGIN_TOP

  // Centred logo
  if (logo) {
    const dims = logo.scaleToFit(160, 55)
    const logoX = (PAGE_WIDTH - dims.width) / 2
    page.drawImage(logo, {
      x: logoX,
      y: y - dims.height,
      width: dims.width,
      height: dims.height,
    })
    y -= dims.height + 10
  }

  // Centred firm name
  const nameWidth = fonts.bold.widthOfTextAtSize(branding.firmName, FONT_TITLE)
  page.drawText(branding.firmName, {
    x: (PAGE_WIDTH - nameWidth) / 2,
    y,
    size: FONT_TITLE,
    font: fonts.bold,
    color: primary,
  })
  y -= 20

  // Centred address
  if (branding.firmAddress) {
    const lines = branding.firmAddress.split('\n')
    for (const line of lines) {
      const lineWidth = fonts.regular.widthOfTextAtSize(line, FONT_BODY)
      page.drawText(line, {
        x: (PAGE_WIDTH - lineWidth) / 2,
        y,
        size: FONT_BODY,
        font: fonts.regular,
        color: NORVA_MID,
      })
      y -= LINE_HEIGHT
    }
  }

  // Centred contact line
  const contactParts: string[] = []
  if (branding.phone) contactParts.push(branding.phone)
  if (branding.fax) contactParts.push(`Fax: ${branding.fax}`)
  if (branding.website) contactParts.push(branding.website)
  if (contactParts.length > 0) {
    const contactLine = contactParts.join('  |  ')
    const contactWidth = fonts.regular.widthOfTextAtSize(contactLine, FONT_SMALL)
    page.drawText(contactLine, {
      x: (PAGE_WIDTH - contactWidth) / 2,
      y,
      size: FONT_SMALL,
      font: fonts.regular,
      color: NORVA_MID,
    })
    y -= LINE_HEIGHT + 2
  }

  // Double-line separator
  y -= 4
  page.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 1.5,
    color: NORVA_ACCENT_LINE,
  })
  y -= 4
  page.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 0.5,
    color: NORVA_LIGHT,
  })
  y -= 16

  return y
}

// ── Layout: Minimal ──────────────────────────────────────────────────────────

function drawMinimalHeader(
  page: PDFPage,
  branding: SovereignBranding,
  fonts: { regular: PDFFont; bold: PDFFont },
): number {
  const primary = getPrimaryColor(branding)
  let y = PAGE_HEIGHT - MARGIN_TOP

  // Firm name only  -  left-aligned, no logo
  page.drawText(branding.firmName, {
    x: MARGIN_LEFT,
    y,
    size: FONT_TITLE,
    font: fonts.bold,
    color: primary,
  })
  y -= 22

  if (branding.firmAddress) {
    const lines = branding.firmAddress.split('\n')
    for (const line of lines) {
      page.drawText(line, {
        x: MARGIN_LEFT, y, size: FONT_BODY, font: fonts.regular, color: NORVA_MID,
      })
      y -= LINE_HEIGHT
    }
  }

  y -= 6
  page.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 0.5,
    color: NORVA_LIGHT,
  })
  y -= 16

  return y
}

// ── Public API: drawSovereignHeader ──────────────────────────────────────────

/**
 * Draws the Sovereign Letterhead header on the given PDF page.
 * Returns the y-position where document content should begin.
 */
export async function drawSovereignHeader(
  doc: PDFDocument,
  page: PDFPage,
  branding: SovereignBranding,
  fonts: { regular: PDFFont; bold: PDFFont },
): Promise<number> {
  const logo = await embedLogo(doc, branding)

  switch (branding.letterheadLayout) {
    case 'modern':
      return drawModernHeader(page, branding, fonts, logo)
    case 'minimal':
      return drawMinimalHeader(page, branding, fonts)
    case 'classic':
    default:
      return drawClassicHeader(page, branding, fonts, logo)
  }
}

// ── Public API: drawSovereignFooter ──────────────────────────────────────────

/**
 * Draws the Sovereign footer on a page.
 * Includes: legal disclaimer (if set) + "Generated by NorvaOS  -  [Firm Name]"
 */
export function drawSovereignFooter(
  page: PDFPage,
  branding: SovereignBranding,
  fonts: { regular: PDFFont; bold: PDFFont },
): void {
  let y = MARGIN_BOTTOM - 10

  // Legal disclaimer
  if (branding.legalDisclaimer) {
    const disclaimerWidth = fonts.regular.widthOfTextAtSize(branding.legalDisclaimer, 6)
    // If it fits on one line, centre it; otherwise left-align
    if (disclaimerWidth <= CONTENT_WIDTH) {
      page.drawText(branding.legalDisclaimer, {
        x: (PAGE_WIDTH - disclaimerWidth) / 2,
        y,
        size: 6,
        font: fonts.regular,
        color: NORVA_LIGHT,
      })
    } else {
      // Wrap to ~2 lines
      const midpoint = Math.ceil(branding.legalDisclaimer.length / 2)
      const breakAt = branding.legalDisclaimer.lastIndexOf(' ', midpoint)
      const line1 = branding.legalDisclaimer.substring(0, breakAt)
      const line2 = branding.legalDisclaimer.substring(breakAt + 1)

      page.drawText(line1, {
        x: MARGIN_LEFT, y, size: 6, font: fonts.regular, color: NORVA_LIGHT,
      })
      y -= 8
      page.drawText(line2, {
        x: MARGIN_LEFT, y, size: 6, font: fonts.regular, color: NORVA_LIGHT,
      })
    }
    y -= 10
  }

  // "Generated by NorvaOS  -  [Firm Name]"
  const footerText = `Generated by NorvaOS  -  ${branding.firmName}`
  const footerWidth = fonts.regular.widthOfTextAtSize(footerText, FONT_SMALL)
  page.drawText(footerText, {
    x: (PAGE_WIDTH - footerWidth) / 2,
    y,
    size: FONT_SMALL,
    font: fonts.regular,
    color: NORVA_LIGHT,
  })
}

// ── Public API: drawSovereignSignature ───────────────────────────────────────

/**
 * Overlays the Principal's digital signature image above a given y-position.
 * Used in retainer agreements and cover letters.
 * Returns the y-position below the signature.
 */
export async function drawSovereignSignature(
  doc: PDFDocument,
  page: PDFPage,
  branding: SovereignBranding,
  opts: {
    x: number
    y: number
    maxWidth?: number
    maxHeight?: number
  },
): Promise<number> {
  const sigImage = await embedSignature(doc, branding)
  if (!sigImage) return opts.y // No signature uploaded  -  return unchanged

  const maxW = opts.maxWidth ?? 150
  const maxH = opts.maxHeight ?? 40
  const dims = sigImage.scaleToFit(maxW, maxH)

  page.drawImage(sigImage, {
    x: opts.x,
    y: opts.y - dims.height,
    width: dims.width,
    height: dims.height,
  })

  return opts.y - dims.height - 4
}

// ── Convenience: Full Branding from Tenant Row ───────────────────────────────

/**
 * Builds a SovereignBranding object from a tenant database row.
 * Logo and signature bytes must be fetched separately and passed in.
 */
export function brandingFromTenant(tenant: {
  name: string
  address_line1?: string | null
  address_line2?: string | null
  city?: string | null
  province?: string | null
  postal_code?: string | null
  country?: string | null
  office_phone?: string | null
  office_fax?: string | null
  primary_color?: string | null
  secondary_color?: string | null
  accent_color?: string | null
  letterhead_layout?: string | null
  legal_disclaimer?: string | null
}, opts?: {
  logoBytes?: Uint8Array | null
  logoMimeType?: 'image/png' | 'image/jpeg' | 'image/svg+xml' | null
  signatureBytes?: Uint8Array | null
}): SovereignBranding {
  // Build address from components
  const addressParts: string[] = []
  if (tenant.address_line1) addressParts.push(tenant.address_line1)
  if (tenant.address_line2) addressParts.push(tenant.address_line2)

  const cityLine: string[] = []
  if (tenant.city) cityLine.push(tenant.city)
  if (tenant.province) cityLine.push(tenant.province)
  if (cityLine.length > 0 && tenant.postal_code) {
    addressParts.push(`${cityLine.join(', ')}  ${tenant.postal_code}`)
  } else if (cityLine.length > 0) {
    addressParts.push(cityLine.join(', '))
  }
  if (tenant.country && tenant.country !== 'CA' && tenant.country !== 'Canada') {
    addressParts.push(tenant.country)
  }

  return {
    firmName: tenant.name,
    firmAddress: addressParts.length > 0 ? addressParts.join('\n') : null,
    logoBytes: opts?.logoBytes ?? null,
    logoMimeType: opts?.logoMimeType ?? null,
    signatureBytes: opts?.signatureBytes ?? null,
    letterheadLayout: (tenant.letterhead_layout as LetterheadLayout) || 'classic',
    primaryColor: tenant.primary_color,
    secondaryColor: tenant.secondary_color,
    accentColor: tenant.accent_color,
    phone: tenant.office_phone,
    fax: tenant.office_fax,
    legalDisclaimer: tenant.legal_disclaimer,
  }
}
